package main

/*
 * This file creates the provenance documents. We have probably two kinds of xml to create.
 * The ones for big dcuments (e.g., full CDA and objects) and the one from ODD. They have
 * the link to the originator one.
 */

import (
	"github.com/beevik/etree"
	"log"
	"os"
	"time"
)

/*
 * This function creates the object/xml provenance structure,
 * which is for the segmented data
 */

func makeProvenanceDocumentSegmented(hashOfTheSegment string, myHash string, agentInfo agent, activity, genTime string) (mapDocument *etree.Document, document string, err error) {
	log.Printf("creating a provenance segmented document")
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0" encoding="UTF-8"`)

	provdocument := doc.CreateElement("prov:document")
	provdocument.CreateAttr("xmlns:prov", "http://www.w3.org/ns/prov#")
	provdocument.CreateAttr("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
	provdocument.CreateAttr("xmlns:ex", "urn:tiani:prova")

	//
	// This is the definition of the entity: here I add a generic "the cda" and
	// it shouldn't bother. This is the originating CDA
	proventity := doc.CreateElement("prov:entity")
	proventity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	proventity.CreateAttr("ns1:id", "theobject")
	provdocument.AddChild(proventity)

	entitylabel := doc.CreateElement("prov:label")
	entitylabel.SetText("The object document")
	proventity.AddChild(entitylabel)

	entitylocationlabel := doc.CreateElement("prov:location")
	proventity.AddChild(entitylocationlabel)

	entitytypelabel := doc.CreateElement("prov:type")
	entitytypelabel.SetText("XML")
	proventity.AddChild(entitytypelabel)

	entityvalue := doc.CreateElement("prov:value")
	entityvalue.SetText(myHash)
	proventity.AddChild(entityvalue)

	

	// now I create another entity with the hash
	provSegEntity := doc.CreateElement("prov:entity")
	provSegEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provSegEntity.CreateAttr("ns1:id", "thesegment")
	provdocument.AddChild(provSegEntity)

	segentitylabel := doc.CreateElement("prov:label")
	segentitylabel.SetText("The CDA Segment")
	provSegEntity.AddChild(segentitylabel)

	segentitytypelabel := doc.CreateElement("prov:type")
	segentitytypelabel.SetText("XML")
	provSegEntity.AddChild(segentitytypelabel)

	segentityvalue := doc.CreateElement("prov:value")
	segentityvalue.SetText(hashOfTheSegment)
	provSegEntity.AddChild(segentityvalue)

	// this is the activity
	provactivity := doc.CreateElement("prov:activity")
	provdocument.AddChild(provactivity)
	provactivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provactivity.CreateAttr("ns1:id", "theobjectcreation")

	activitytype := doc.CreateElement("prov:type")
	activitytype.SetText(activity)
	provactivity.AddChild(activitytype)

	// this is the agent
	provagent := doc.CreateElement("prov:agent")
	provdocument.AddChild(provagent)
	provagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provagent.CreateAttr("ns1:id", agentInfo.id)

	agenttype := doc.CreateElement("prov:type")
	agenttype.SetText(agentInfo.atype)
	provagent.AddChild(agenttype)

	agentDocId := doc.CreateElement("hpd:doctorid")
	provagent.AddChild(agentDocId)
	agentDocId.CreateAttr("xmlns:hpd", "IHEHPD")
	agentDocId.SetText(agentInfo.id)

	agentDocName := doc.CreateElement("hpd:doctorname")
	provagent.AddChild(agentDocName)
	agentDocName.CreateAttr("xmlns:hpd", "IHEHPD")
	agentDocName.SetText(agentInfo.name)

	agentDocIdp := doc.CreateElement("hpd:idp")
	provagent.AddChild(agentDocIdp)
	agentDocIdp.CreateAttr("xmlns:hpd", "idp")
	agentDocIdp.SetText(agentInfo.identityProvider)
	
	// Now we need to say what happened. Basically here we create
	// that the entity has been generated by the activity, whose activity was
	// associated with an agent, and the eneity was attributed to the agent

	provWasGeneratedBy := doc.CreateElement("prov:wasGeneratedBy")
	provdocument.AddChild(provWasGeneratedBy)
	provWasGenEntity := doc.CreateElement("prov:entity")
	provWasGeneratedBy.AddChild(provWasGenEntity)
	provWasGenEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasGenEntity.CreateAttr("ns1:ref", "thesegment")
	provWasGenActivity := doc.CreateElement("prov:activity")
	provWasGeneratedBy.AddChild(provWasGenActivity)
	provWasGenActivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasGenActivity.CreateAttr("ns1:ref", "theobjectcreation")
	provWasGenTime := doc.CreateElement("prov:time")
	provWasGeneratedBy.AddChild(provWasGenTime)
	//provWasGenTime.SetText(time.Now().UTC().Format(genTime))
	t,errTime := time.Parse("2006-01-02T15:04:05.000Z", genTime)
	
	if errTime != nil{
		return nil,"",errTime
	} 
	
	provWasGenTime.SetText(t.String())

	// Now, who created the docuemnt, firstly we know that the agent perfomed an
	// activity, than that the entity was attributed to the agent

	provWasAssociatedWith := doc.CreateElement("prov:wasAssociatedWith")
	provdocument.AddChild(provWasAssociatedWith)
	provWasAssactivity := doc.CreateElement("prov:activity")
	provWasAssociatedWith.AddChild(provWasAssactivity)
	provWasAssactivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAssactivity.CreateAttr("ns1:ref", "theobject")
	provWasAssagent := doc.CreateElement("prov:agent")
	provWasAssociatedWith.AddChild(provWasAssagent)
	provWasAssagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAssagent.CreateAttr("ns1:ref", agentInfo.id)

	// Used
	provUsed := doc.CreateElement("prov:used")
	provdocument.AddChild(provUsed)
	provUsedactivity := doc.CreateElement("prov:activity")
	provUsed.AddChild(provUsedactivity)
	provUsedactivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provUsedactivity.CreateAttr("ns1:ref", "theobjectcreation")
	provUsedagent := doc.CreateElement("prov:entity")
	provUsed.AddChild(provUsedagent)
	provUsedagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provUsedagent.CreateAttr("ns1:ref", agentInfo.id)

	// Was derivedFrom
	provWasDerivedFrom := doc.CreateElement("prov:wasDerivedFrom")
	provdocument.AddChild(provWasDerivedFrom)
	provUsedGeneratedEntity := doc.CreateElement("prov:generatedEntity")
	provWasDerivedFrom.AddChild(provUsedGeneratedEntity)
	provUsedGeneratedEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provUsedGeneratedEntity.CreateAttr("ns1:ref", "thesegment")
	provUsedEntity := doc.CreateElement("prov:usedEntity")
	provWasDerivedFrom.AddChild(provUsedEntity)
	provUsedEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provUsedEntity.CreateAttr("ns1:ref", "theobject")
	mydocument, err := doc.WriteToString()
	if err != nil {
		return nil,"",err
	}
	doc.WriteTo(os.Stdout)
	return doc, mydocument,nil
}

/*
 * This function creates the object/xml provenance structure
 */

func makeProvenanceDocument(myHash string, agentInfo agent, activity, genTime string) (provdoc *etree.Document, docAsStr string, err error) {
	log.Printf("creating a provenance document")
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0" encoding="UTF-8"`)

	provdocument := doc.CreateElement("prov:document")
	provdocument.CreateAttr("xmlns:prov", "http://www.w3.org/ns/prov#")
	provdocument.CreateAttr("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
	provdocument.CreateAttr("xmlns:ex", "urn:tiani:prova")

	//
	// This is the definition of the entity: here I add a generic "the cda" and
	// it shouldn't bother
	proventity := doc.CreateElement("prov:entity")
	proventity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	proventity.CreateAttr("ns1:id", "theobject")
	provdocument.AddChild(proventity)

	entitylabel := doc.CreateElement("prov:label")
	entitylabel.SetText("The object document")
	proventity.AddChild(entitylabel)

	entitylocationlabel := doc.CreateElement("prov:location")
	proventity.AddChild(entitylocationlabel)

	entitytypelabel := doc.CreateElement("prov:type")
	entitytypelabel.SetText("XML")
	proventity.AddChild(entitytypelabel)

	entityvalue := doc.CreateElement("prov:value")
	entityvalue.SetText(myHash)
	proventity.AddChild(entityvalue)


	// this is the activity
	provactivity := doc.CreateElement("prov:activity")
	provdocument.AddChild(provactivity)
	provactivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provactivity.CreateAttr("ns1:id", "theobjectcreation")

	activitytype := doc.CreateElement("prov:type")
	activitytype.SetText(activity)
	provactivity.AddChild(activitytype)

	// this is the agent
	provagent := doc.CreateElement("prov:agent")
	provdocument.AddChild(provagent)
	provagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provagent.CreateAttr("ns1:id", agentInfo.id)

	agenttype := doc.CreateElement("prov:type")
	agenttype.SetText(agentInfo.atype)
	provagent.AddChild(agenttype)

	agentDocId := doc.CreateElement("hpd:doctorid")
	provagent.AddChild(agentDocId)
	agentDocId.CreateAttr("xmlns:hpd", "IHEHPD")
	agentDocId.SetText(agentInfo.id)

	agentDocName := doc.CreateElement("hpd:doctorname")
	provagent.AddChild(agentDocName)
	agentDocName.CreateAttr("xmlns:hpd", "IHEHPD")
	agentDocName.SetText(agentInfo.name)
	
	agentDocIdp := doc.CreateElement("hpd:idp")
	provagent.AddChild(agentDocIdp)
	agentDocIdp.CreateAttr("xmlns:hpd", "idp")
	agentDocIdp.SetText(agentInfo.identityProvider)

	// Now we need to say what happened. Basically here we create
	// that the entity has been generated by the activity, whose activity was
	// associated with an agent, and the eneity was attributed to the agent

	provWasGeneratedBy := doc.CreateElement("prov:wasGeneratedBy")
	provdocument.AddChild(provWasGeneratedBy)
	provWasGenEntity := doc.CreateElement("prov:entity")
	provWasGeneratedBy.AddChild(provWasGenEntity)
	provWasGenEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasGenEntity.CreateAttr("ns1:ref", "theobject")
	provWasGenActivity := doc.CreateElement("prov:activity")
	provWasGeneratedBy.AddChild(provWasGenActivity)
	provWasGenActivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasGenActivity.CreateAttr("ns1:ref", "theobjectcreation")
	provWasGenTime := doc.CreateElement("prov:time")
	provWasGeneratedBy.AddChild(provWasGenTime)
	t,errTime := time.Parse("2006-01-02T15:04:05.000Z", genTime)
	if errTime != nil{
		return nil,"",errTime
	} 
	
	provWasGenTime.SetText(t.String())

	// Now, who created the docuemnt, firstly we know that the agent perfomed an
	// activity, than that the entity was attributed to the agent

	provWasAssociatedWith := doc.CreateElement("prov:wasAssociatedWith")
	provdocument.AddChild(provWasAssociatedWith)
	provWasAssactivity := doc.CreateElement("prov:activity")
	provWasAssociatedWith.AddChild(provWasAssactivity)
	provWasAssactivity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAssactivity.CreateAttr("ns1:ref", "theobject")
	provWasAssagent := doc.CreateElement("prov:agent")
	provWasAssociatedWith.AddChild(provWasAssagent)
	provWasAssagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAssagent.CreateAttr("ns1:ref", agentInfo.id)

	provWasAttributedTo := doc.CreateElement("prov:wasAttributedTo")
	provdocument.AddChild(provWasAttributedTo)
	provWasAttributedToEntity := doc.CreateElement("prov:entity")
	provWasAttributedTo.AddChild(provWasAttributedToEntity)
	provWasAttributedToEntity.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAttributedToEntity.CreateAttr("ns1:ref", "theobject")
	provWasAttributeToagent := doc.CreateElement("prov:agent")
	provWasAttributedTo.AddChild(provWasAttributeToagent)
	provWasAttributeToagent.CreateAttr("xmlns:ns1", "http://www.w3.org/ns/prov#")
	provWasAttributeToagent.CreateAttr("ns1:ref", agentInfo.id)

	docAsString, err := doc.WriteToString()
	if err != nil {
		return nil,"",err
	}
	doc.WriteTo(os.Stdout)

	return doc, docAsString,nil
}
